-- Migration: Create Blog Articles Table
-- Description: Create table for storing blog articles with SEO metadata
-- Created: 2025-12-10

-- Create blog_articles table
CREATE TABLE IF NOT EXISTS blog_articles (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Article Identity
  city VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  slug VARCHAR(500) NOT NULL,
  
  -- Content
  title VARCHAR(500) NOT NULL,
  content TEXT NOT NULL, -- HTML from React-Quill
  
  -- SEO Fields
  seo_keywords TEXT,
  meta_description VARCHAR(500),
  featured_image TEXT, -- URL to featured image
  
  -- Publication Status
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  
  -- AI Generation Metadata
  generated_by VARCHAR(100) NOT NULL, -- e.g., 'claude-3-5-sonnet'
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Publication Timestamps
  published_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Optional Event References
  event_ids UUID[], -- Array of event IDs mentioned in article
  
  -- Constraints
  CONSTRAINT unique_city_category_slug UNIQUE (city, category, slug)
);

-- Create indexes for performance
CREATE INDEX idx_blog_articles_city ON blog_articles(city);
CREATE INDEX idx_blog_articles_category ON blog_articles(category);
CREATE INDEX idx_blog_articles_status ON blog_articles(status);
CREATE INDEX idx_blog_articles_published_at ON blog_articles(published_at DESC) WHERE published_at IS NOT NULL;
CREATE INDEX idx_blog_articles_updated_at ON blog_articles(updated_at DESC);
CREATE INDEX idx_blog_articles_slug ON blog_articles(slug);

-- Create composite index for common queries
CREATE INDEX idx_blog_articles_city_category_status ON blog_articles(city, category, status);

-- Add trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_blog_articles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_blog_articles_updated_at
  BEFORE UPDATE ON blog_articles
  FOR EACH ROW
  EXECUTE FUNCTION update_blog_articles_updated_at();

-- Add trigger to set published_at when status changes to 'published'
CREATE OR REPLACE FUNCTION set_blog_articles_published_at()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'published' AND OLD.status != 'published' AND NEW.published_at IS NULL THEN
    NEW.published_at = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_blog_articles_published_at
  BEFORE UPDATE ON blog_articles
  FOR EACH ROW
  EXECUTE FUNCTION set_blog_articles_published_at();

-- Add comment for documentation
COMMENT ON TABLE blog_articles IS 'Blog articles generated by AI for event categories and cities';
COMMENT ON COLUMN blog_articles.slug IS 'URL-safe slug generated from title, format: city-category-normalized-title';
COMMENT ON COLUMN blog_articles.generated_by IS 'AI model used to generate the article (e.g., claude-3-5-sonnet)';
COMMENT ON COLUMN blog_articles.event_ids IS 'Array of event UUIDs referenced in the article';
