-- ============================================================================
-- SUPABASE STORAGE: EVENT-IMAGES BUCKET POLICIES
-- ============================================================================
--
-- The "event-images" bucket already exists (used by das Werk scraper).
-- This file documents the required policies for the AI search image upload.
--
-- ============================================================================
-- REQUIRED POLICIES (Add via Supabase Dashboard if missing):
-- ============================================================================
--
-- Go to: Storage > event-images > Policies
--
-- Policy 1: Public Read (for CDN access)
--   Operation: SELECT
--   Roles: public
--   USING: bucket_id = 'event-images'
--
-- Policy 2: Service Role Upload (for image upload)
--   Operation: INSERT
--   Roles: service_role
--   WITH CHECK: bucket_id = 'event-images'
--
-- ============================================================================
-- VERIFY POLICIES:
-- ============================================================================
--
-- SELECT policyname, roles, cmd
-- FROM pg_policies
-- WHERE schemaname = 'storage' AND tablename = 'objects'
-- AND (policyname LIKE '%event%' OR policyname LIKE '%image%');
--
-- ============================================================================

SELECT 'event-images bucket exists - verify policies in Dashboard' as notice;
